spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/Dev/IdeaProjects/jpashop/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true # System.out 으로 출력 사용 X
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # Logger 출력
    org.hibernate.type: trace